CREATE TABLE IF NOT EXISTS root_entity(
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT
);

CREATE TABLE IF NOT EXISTS child_entity(
  ID BIGSERIAL PRIMARY KEY,
  ROOT_ENTITY_ID BIGINT REFERENCES root_entity(id),
  CREATED_AT TIMESTAMPTZ
);